FatalOnErr = true
InType = "json"
MustInArray = false
In = "./in"
InTemp = "./temp"
OutType = "json"
Out = "./out"

[Service]
Port = 1329
API = "/weight"

[Weighting]
StudentIDPath = "otf.id.studentID"
DomainPath = "meta.capability"
TimePath="meta.readTimestampUTC"
ScorePath = "otf.level.calculatedScore.scaledScore"