FatalOnErr = true
InType = "json"
MustInArray = false
In = "./in"
InTemp = "./temp"
OutType = "json"
Out = "./out"

[Service]
Port = 1329
API = "/weight"

[Weighting]
StudentIDPath = "otf.id.studentID"
ProgressionLevelPath = "otf.progressionLevel"
TimePath0 = "original.test.date_administered"
TimePath1 = "meta.readTimestampUTC"
ScorePath = "otf.level.calculatedScore.scaledScore"
